spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true          # ???????? ????????? Eureka ??? ??????????? ????????
      service-id: gateway    # ???????? ????? ??????? ? Eureka
    gateway:
      routes:
        - id: ruleset_route
          uri: lb://RULESET-SERVICE
          predicates:
            - Path=/api/rulesets/**
        - id: job_route
          uri: lb://JOB-SERVICE
          predicates:
            - Path=/api/jobs/**
        - id: file_route
          uri: lb://FILE-PROCESSING-SERVICE
          predicates:
            - Path=/files/**

server:
  port: 8080  # ????, ?? ??????? ????? ???????? Gateway
